import type { AppProps } from 'next/app'
import { NextPage } from 'next'
import ThemeContextProvider from '../hooks/useTheme'
import Head from 'next/head'

const MyApp: NextPage<AppProps> = ({ Component, pageProps }) => {
  return (
    <ThemeContextProvider>
      <Head>
        <title>Template Next.js</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Component {...pageProps} />
    </ThemeContextProvider>
  )

}

export default MyApp
