import type { AppProps } from 'next/app'
import { NextPage } from 'next'
import ThemeContextProvider from '../hooks/useTheme'
import Head from 'next/head'
import Script from 'next/script'
import { useEffect, useState } from 'react'

const MyApp: NextPage<AppProps> = ({ Component, pageProps }) => {
  const [isMounted, setIsMounted] = useState(false);

  useEffect(() => {
    setIsMounted(true);
  }, []);
  return (
    <ThemeContextProvider>
      <Head>
        <title>Template Next.js</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {isMounted && <Component {...pageProps} />}
    </ThemeContextProvider>
  );

}

export default MyApp
