import type { NextPage } from 'next'
import Head from 'next/head'
import light from '../styles/themes/light'
import dark from '../styles/themes/dark'
import { useState } from 'react'
import { ThemeProvider } from 'styled-components'
import GlobalStyles from '../styles/global'
import { Container, Header, Main } from '../styles/Pages/Home'
import Toggle from './_components/_toggle'


const Home: NextPage = () => {
  const [theme, setTheme] = useState(light)

  const toggleTheme = () => {
    setTheme(theme.title === 'light' ? dark : light)
  }
  return (
    <ThemeProvider theme={theme}>
      <Container>
        <Head>
          <title>Template Next.js</title>
          <meta name="description" content="Generated by create next app" />
        </Head>

        <Header>
          <Toggle toggleTheme={toggleTheme}/>
        </Header>

        <Main>
          <h1>Default Template Next.js</h1>
          <p>
            Este é um template base para projetos Next.js que contem Typescript,
            Tailwind, Twin.macro e Styled Components
          </p>
        </Main>

        <footer></footer>
      </Container>
      <GlobalStyles />
    </ThemeProvider>
  )
}

export default Home
