import type { NextPage } from 'next'
import Head from 'next/head'
import { Container } from '../styles/Pages/Home'

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Template Next.js</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1>Default Template Next.js</h1>
        <p>Este é um template base para projetos Next.js que contem Typescript, Tailwind, Twin.macro e Styled Components</p>
      </main>

      <footer>
      </footer>
    </Container>
  )
}

export default Home
